export * from "./dashboardIcon";
export * from "./deviceicon";
export * from './bellIcon';
export * from './IconReport'
export * from './IconSetting'
export * from './IconService'
export * from './IconNumber'
export * from './IconNumberProvied'
export * from './IconArrow'
export * from './IconAddDevice'
export * from './IconNumberOrdered'
export * from './IconNumberUserWait'
export * from './IconUserShiped'
export * from './IconLogout'